name: Metrics
on:
  # Schedule daily updates
  # schedule: [{cron: "0 0 * * *"}]
  # (optional) Run workflow manually
  workflow_dispatch:
  # (optional) Run workflow when pushing on master/main
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    environment:
      name: production
    permissions:
      contents: write
    steps:

        - name: Metrics
          if: ${{ success() || failure() }}
          uses: lowlighter/metrics@latest
          with:
            filename: metrics.plugin.isocalendar.svg
            token: ${{ secrets.METRICS_TOKEN }}
            base: ""
            plugin_topics: yes
            plugin_topics_limit: 20
            plugin_topics_mode: icons
            plugin_lines: yes
            # plugin_isocalendar: yes
            # plugin_languages: yes
            # plugin_languages_details: bytes-size, percentage
            # plugin_languages_sections: most-used, recently-used
            # plugin_languages_indepth: yes
            # plugin_languages_limit: 4
            # plugin_achievements: yes
            # plugin_achievements_display: compact
            plugin_calendar: yes
            plugin_calendar_limit: 3
            
